### PR TITLE
Document ALL the things 

### PR DESCRIPTION
**Pull request by brianamarie**
Based on the great work done [on teacher-bot proper by @crichID](https://github.com/teacher-bot/teacherbot/pull/4/), this pull request attempts to add documentation to match the [probot/plugin-template](https://github.com/probot/plugin-template). 

I will `@mention` once it's ready for review. 👍 

ToDo: Review all files to make sure they match 🤷‍♀️ 
- [x] docs/deploy
- [x] .env.example
- [x] .gitignore
- [x] .travis.yml
- [x] LICENSE 
- [x] README.md
- [x] app.json
- [x] index.js
- [x] package.json
- [x] `package-lock.json` = delete package-lock.json file
- [x] Remove .travis.yml file and app.json file
- [x] README with the appropriate information on configuration and the permission

### CODE REVIEW

**Comment by brianamarie** [comment]
@teacher-bot/training-team This is ready for review 🎉 

Two questions: 
- Do we want to run Travis on this repository?
- The package-lock.json file isn't updated with the new info in package.json. Is this a big deal? 

cc @crichID especially since she has done this once before

**Comment by brianamarie** [comment]
_Removed comment here to update OP_

**Comment by brianamarie** [comment]
@teacher-bot/training-team Since our meeting today, I've 
- deleted `app.json`
- deleted `.travis.yml`
- deleted `.package-lock.json`
- added configuration and permission information to README.md 

This is ready for 👀, especially the `README.md`.

**Comment by crichID** [comment]
add-collabs

@brianamarie just dropping your :sparkles: gif here so we can include it elsewhere.

**Review by crichID — APPROVED** [review]
@brianamarie I think this looks :sparkles:. Thank you for getting this documentation whipped in to shape so quickly.

**Pull request merged**
